package constants

type Endpoint = string

const (
	V1AccessTokenEndpoint        Endpoint = "/api/1/access_token"
	V1Nomenclature               Endpoint = "/api/1/nomenclature"
	V2Menu                       Endpoint = "/api/2/menu"
	V2MenuByID                   Endpoint = "/api/2/menu/by_id"
	V1Organizations              Endpoint = "/api/1/organizations"
	V1PaymentTypes               Endpoint = "/api/1/payment_types"
	V1CalculateCheckin           Endpoint = "/api/1/loyalty/iiko/calculate"
	V1CancelHoldMoney            Endpoint = "/api/1/loyalty/iiko/customer/wallet/cancel_hold"
	V1CreateOrder                Endpoint = "/api/1/order/create"
	V1AvailableRestaurantSection Endpoint = "/api/1/reserve/available_restaurant_sections"
	V1TerminalGroups             Endpoint = "/api/1/terminal_groups"
	V1StopLists                  Endpoint = "/api/1/stop_lists"
	V1Streets                    Endpoint = "/api/1/streets"
	V1Cities                     Endpoint = "/api/1/cities"
	V1Regions                    Endpoint = "/api/1/regions"
	V1DeliveryOrdersByID         Endpoint = "/api/1/deliveries/by_id"
	V1OrdersByID                 Endpoint = "/api/1/orders/by_id"
	V1CustomerByID               Endpoint = "/api/1/loyalty/iiko/customer/get_by_id"
	V1CustomerCreateOrUpdate     Endpoint = "/api/1/loyalty/iiko/customer/create_or_update"
	V1MarketingCampaigns         Endpoint = "/api/1/marketing_campaigns"
	V1Coupons                    Endpoint = "/api/1/loyalty/iiko/coupons"
	V1CouponsByID                Endpoint = "/api/1/loyalty/iiko/coupons/by_id"
	V1OrderStatus                Endpoint = "/api/1/orders/status"
	V1CloseOrder                 Endpoint = "/api/1/orders/close"
	V1CancelOrder                Endpoint = "/api/1/orders/cancel"
	V1DeliveriesByID             Endpoint = "/api/1/deliveries/by_id"
	V1DeliveriesStatus           Endpoint = "/api/1/deliveries/status"
	V1CustomerSearch             Endpoint = "/api/1/loyalty/iiko/customer/search"
	V1CustomerWalletBalance      Endpoint = "/api/1/loyalty/iiko/customer/wallet/balance"
	V1CustomerWalletHistory      Endpoint = "/api/1/loyalty/iiko/customer/wallet/history"
	V1CustomerWalletHold         Endpoint = "/api/1/loyalty/iiko/customer/wallet/hold"
	V1CustomerWalletRefund       Endpoint = "/api/1/loyalty/iiko/customer/wallet/refund"
	V1OrderTypes                 Endpoint = "/api/1/order_types"
	V1DeliveryZones              Endpoint = "/api/1/delivery/zones"
	V1MarketingSources           Endpoint = "/api/1/marketing_sources"
	V1Operators                  Endpoint = "/api/1/operators"
	V1Employees                  Endpoint = "/api/1/employees"
	V1DiscountTypes              Endpoint = "/api/1/discounts"
	V1TipsTypes                  Endpoint = "/api/1/tips"
	V1Tables                     Endpoint = "/api/1/tables"
)
